export const LEADING_DIGIT_FREQ_SELECTION = "LEADING_DIGIT_FREQ_SELECTION";
export const LEADING_DIGIT_FREQ_CLEAR_SELECTION = "LEADING_DIGIT_FREQ_CLEAR_SELECTION";
export const FREQUENT_VALUES_SELECTION = "FREQUENT_VALUES_SELECTION";
export const FREQUENT_VALUES_CLEAR_SELECTION = "FREQUENT_VALUES_CLEAR_SELECTION";
export type DuplicateCountType = 'ALL' | 'TOP';
export type FilterAction = 'FILTER_ADDED' | 'FILTER_REMOVED';